### PR TITLE
Added view for making releases read only

### PR DESCRIPTION
**Pull request by nurav**
Added a button that enables users to change the read-only state of a release. This button is red for read only releases and white for others.

### CODE REVIEW

**Comment by nurav** [comment]
Other methods of changing a release (deletes, updates) still need proper error-handling for read-only releases, right now, they just fail silently.

**Comment by bhearsum** [comment]
What does "silently" mean? Do they pop an error dialog at all?

**Comment by bhearsum** [comment]
The UI seems OK to me: http://people.mozilla.org/~bhearsum/sattap/1c0c05b3.png. Definitely need something better for failed deletes, though.

**Comment by nurav** [comment]
Oh, I must have done something wrong when I tested the update modal. I'll see what I can do about the delete modal.

**Comment by bhearsum** [comment]
I like the new UI a lot, but I found a one or two bugs. Specifically:
* After a full page refresh I change a read-only release to modifiable, then tried to update it. I got this error: http://people.mozilla.org/~bhearsum/sattap/815cc76d.png, and this in the server logs:

> balrogadmin_1 | 2016-04-05 18:20:23,738 - WARNING - PID: 11 - Request: 140375959640592 - SingleReleaseView._put#249: Bad input: Couldn't update release: update: old_data_version must be passed for Tables that are versioned

* If I try to change the state of release twice (eg: read only -> modifiable -> read only), the modal changes to the opposite one (if it said "make this release read only" it changes to "make this release read/write", and an error in the console similar to above:

> balrogadmin_1 | 2016-04-05 18:21:10,214 - ERROR - PID: 11 - Request: 140375950567440 - auslib.admin.base.log_exception#1423: Exception on /releases/B2G-dogfood-fota-20151130130150/read_only [PUT]
> balrogadmin_1 | Traceback (most recent call last):
> balrogadmin_1 |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
> balrogadmin_1 |     response = self.full_dispatch_request()
> balrogadmin_1 |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
> balrogadmin_1 |     rv = self.handle_user_exception(e)
> balrogadmin_1 |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
> balrogadmin_1 |     reraise(exc_type, exc_value, tb)
> balrogadmin_1 |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
> balrogadmin_1 |     rv = self.dispatch_request()
> balrogadmin_1 |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
> balrogadmin_1 |     return self.view_functions[rule.endpoint](**req.view_args)
> balrogadmin_1 |   File "/usr/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
> balrogadmin_1 |     return self.dispatch_request(*args, **kwargs)
> balrogadmin_1 |   File "/usr/local/lib/python2.7/site-packages/flask/views.py", line 149, in dispatch_request
> balrogadmin_1 |     return meth(*args, **kwargs)
> balrogadmin_1 |   File "./auslib/admin/views/base.py", line 51, in decorated
> balrogadmin_1 |     return f(*args, **kwargs)
> balrogadmin_1 |   File "./auslib/admin/views/base.py", line 76, in put
> balrogadmin_1 |     return self._put(*args, transaction=trans, **kwargs)
> balrogadmin_1 |   File "./auslib/admin/views/base.py", line 76, in put
> balrogadmin_1 |     return self._put(*args, transaction=trans, **kwargs)
> balrogadmin_1 |   File "./auslib/admin/views/base.py", line 19, in decorated
> balrogadmin_1 |     return f(*args, changed_by=username, **kwargs)
> balrogadmin_1 |   File "./auslib/admin/views/base.py", line 42, in decorated
> balrogadmin_1 |     return f(*args, **kwargs)
> balrogadmin_1 |   File "./auslib/admin/views/releases.py", line 348, in _put
> balrogadmin_1 |     dbo.releases.updateRelease(release, changed_by, form.data_version.data, read_only=False, transaction=transaction)
> balrogadmin_1 |   File "./auslib/db.py", line 1051, in updateRelease
> balrogadmin_1 |     self.update(where=[self.name == name], what=what, changed_by=changed_by, old_data_version=old_data_version, transaction=transaction)
> balrogadmin_1 |   File "./auslib/db.py", line 426, in update
> balrogadmin_1 |     raise ValueError("update: old_data_version must be passed for Tables that are versioned")
> balrogadmin_1 | ValueError: update: old_data_version must be passed for Tables that are versioned


It looks like there might be a bug around setting data_version properly in the UI after making a change to the read-only flag?

**Comment by nurav** [comment]
Hmph, I had these errors earlier and I though I'd fixed them. You're right, it has to do with setting the data_version incorrectly.

**Comment by nurav** [comment]
Oh wait. @bhearsum, you'll have to update the balrog server code to use https://github.com/mozilla/balrog/pull/67, since we weren't sending back the new data version to the UI earlier.

**Comment by bhearsum** [comment]
Oh, duh! Works fine if I test against that version of the backend!

**Pull request merged**
