### PR TITLE
Server-side pagination of history views

### PR DESCRIPTION
**Pull request by njirap**

### CODE REVIEW

**Comment by mozbhearsum** [comment]
This PR fixes the issues noted in https://bugzilla.mozilla.org/show_bug.cgi?id=1163160#c5, but there's a new one: The pagination controls always show enough pages to hold all items, not just the filtered ones. Eg: if I filter on "Firefox" rules in the sample data, I have 15 pages. But only the first 6 have any items in them. I think this is due to replacing filtered_items with rules_count on the pagination controls. What's tricky here, which I think you already realized, is that the number of pages is calculated different in the main rules view vs. the history.

You asked previously if we could do incremental loading on the main rules/releases page as well, but I don't think we can. Because of the way filtering works, we must have all items available for the UI work. I can definitely see the benefit of unifying the way history and non-history views work, though. Perhaps it's best if we get rid of the incremental loading on the history views instead? The releases views will be slow to load for the moment if you do that, but could be fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1284385.

Let me know what you think.

**Comment by mozbhearsum** [comment]
Pagination looks to be fully working on the Rules and Rule history pages, so that's good. There's a small bug in the Releases view though - the pagination control and "N found" don't work when filtering. For example, I end up with 3 releases but 8 pages if I filter on "44.0b": http://people.mozilla.org/~bhearsum/sattap/9a8f2b94.png

**Comment by mozbhearsum** [comment]
It looks like that error was something on the NPM server. I retried it in https://tools.taskcluster.net/task-inspector/#Q-kJCv4uSaOGgE5Ixv70KQ/0, and it passed there.

**Comment by mozbhearsum** [comment]
The latest push fixes the issue from my July 15th comment, but it looks like pagination is now busted on the Releases History view. Eg: http://localhost:8080/releases/Firefox-44.0b2-build1 only shows one page worth of history, even though http://localhost:8080/api/releases/Firefox-44.0b2-build1/revisions?limit=10&page=1 says there's 451 total revisions. It works fine with Rules history - I think the response from Releases.getHistory is being handled incorrectly?

**Comment by njirap** [comment]
Hi @mozbhearsum ..the other backend PR was also ready yesterday..

https://github.com/mozilla/balrog/pull/100

**Comment by mozbhearsum** [comment]
Everything looks good now, I'm going to get this and the backend change merged. Thank you!!

**Pull request merged**
