### PR TITLE
(Fix #1281912) Rules pagination bad wrapping

### PR DESCRIPTION
**Pull request by njirap**
In the Rules index and history views the filter section
appears to have more allocated space than it needs. This change
reduces from there and adds to the pagination widget to allow
for the elasticity of the same without ugly wrapping to the next line

### CODE REVIEW

**Comment by mozbhearsum** [comment]
This fixes the paginator, but it breaks the layout of the dropdown labels on the main rules page :(, eg: http://people.mozilla.org/~bhearsum/sattap/767ebc8c.png

A couple of ideas to fix it:
* Decrease the number of clickable pages in the paginator
* Widen the overall layout (do this on all pages if you do it here)

I'm open to other ideas too.

**Comment by mozbhearsum** [comment]
Whoops, I hadn't noticed that you updated this! Looks perfect now, I'll sort out the merge conflicts on my side and get it merged.

**Comment by mozbhearsum** [comment]
Are you making a new branch for this, @njirap? It hasn't been merged yet...

**Comment by njirap** [comment]
Wow I deleted it...!!!! Let me try bring it up again..

**Pull request closed without merging**
